batch_size: 128
channels: 3
data_path: ./Data/rgb
lab_classes:
- dog
- flower
model_train_path: ./train_checkpoint/
test_perc: 0.3
learning_rate: 0.01
momentum: 0.5
num_epochs: 30
J: 6
imageSize: !!python/tuple
- 128
- 128
n_rotations: 8
order: 2
