batch_size: 12
channels: 1
data_path: ./Data/gray
imageSize: !!python/tuple
- 128
- 128
lab_classes:
- dog
- whale
model_train_path: ./train_checkpoint/
test_perc: 0.2
learning_rate: 0.001
momentum: 0.5
num_epochs: 50
