augmentations: 0
batch_size: 64
channels: 1
data_path: ./Data/gray
epoch_val: 1
imageSize: !!python/tuple
- 100
- 100
lab_classes:
- pos
- neg
model_train_path: ./train_checkpoint/
num_k_folds: 3
num_samples: 216
optimizer: 0
results_path: ./results/
test_perc: 0.2
weight_decay: 0.01
learning_rate: 0.005
momentum: 0.9
num_epochs: 100
