batch_size: 64
channels: 1
data_path: ./Data/gray
lab_classes:
- flower
- dog
model_train_path: ./train_checkpoint/
results_path: ./results/
test_perc: 0.2
training_data_size: 500
learning_rate: 0.001
momentum: 0.9
num_epochs: 100
J: 32
imageSize: !!python/tuple
- 128
- 128
n_rotations: 8
order: 2
