batch_size: 64
channels: 1
data_path: ./Data/gray
lab_classes:
- flower
- dog
model_train_path: ./train_checkpoint/
test_perc: 0.2
learning_rate: 0.01
momentum: 0.5
num_epochs: 50
J: 32
imageSize: !!python/tuple
- 128
- 128
n_rotations: 6
order: 2
