batch_size: 12
channels: 3
data_path: ./Data/rgb
lab_classes:
- dog
- flower
model_train_path: ./train_checkpoint/
test_perc: 0.2
learning_rate: 0.001
momentum: 0.5
num_epochs: 50
J: 6
imageSize: !!python/tuple
- 128
- 128
n_rotations: 8
order: 2
