batch_size: 64
channels: 1
data_path: ./Data/gray
imageSize: !!python/tuple
- 128
- 128
lab_classes:
- flower
- dog
model_train_path: ./train_checkpoint/
num_samples: 500
results_path: ./results/
test_perc: 0.2
learning_rate: 0.001
momentum: 0.5
num_epochs: 100
