batch_size: 64
channels: 3
data_path: ./Data/rgb
lab_classes:
- dog
- whale
model_train_path: ./train_checkpoint/
test_perc: 0.2
learning_rate: 0.0001
momentum: 0.9
num_epochs: 50
J: 32
imageSize: !!python/tuple
- 128
- 128
n_rotations: 8
order: 2
