batch_size: 64
data_path: ./Data
lab_classes:
- dog
- flower
model_train_path: ./train_checkpoint
test_perc: 0.3
learning_rate: 0.01
momentum: 0.5
num_epochs: 80
J: 2
imageSize: !!python/tuple
- 128
- 128
order: 2
