batch_size: 25
channels: 3
data_path: ./Data/rgb
lab_classes:
- dog
- flower
model_train_path: ./train_checkpoint/
test_perc: 0.3
learning_rate: 0.001
momentum: 0.9
num_epochs: 30
J: 64
imageSize: !!python/tuple
- 128
- 128
n_rotations: 4
order: 2
