augmentations: 16
batch_size: 64
channels: 1
data_path: ./Data/gray
epoch_val: 1
imageSize: !!python/tuple
- 128
- 128
lab_classes:
- dog
- flower
model_train_path: ./train_checkpoint/
num_k_folds: 3
num_samples: 2500
optimizer: 0
results_path: ./results/
test_perc: 0.2
weight_decay: 0.01
learning_rate: 0.005
momentum: 0.9
num_epochs: 100
